<?php

namespace Tests\Feature;

use App\Models\College;
use App\Models\Department;
use App\Models\Student;
use App\Models\Teacher;
use App\Models\University;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AutoGeneratedAcademicIdsTest extends TestCase
{
    use RefreshDatabase;

    public function test_student_id_is_auto_generated_when_missing(): void
    {
        [$university, $department] = $this->organization();

        $first = Student::create([
            'university_id' => $university->id,
            'department_id' => $department->id,
            'full_name' => 'Generated Student One',
            'email' => 'generated.student.one@example.com',
            'status' => 'Active',
        ]);

        $second = Student::create([
            'university_id' => $university->id,
            'department_id' => $department->id,
            'full_name' => 'Generated Student Two',
            'email' => 'generated.student.two@example.com',
            'status' => 'Active',
        ]);

        $this->assertNotEmpty($first->student_id);
        $this->assertNotEmpty($second->student_id);
        $this->assertStringStartsWith('STD', $first->student_id);
        $this->assertStringStartsWith('STD', $second->student_id);
        $this->assertStringNotContainsString('-', $first->student_id);
        $this->assertStringNotContainsString('-', $second->student_id);
        $this->assertMatchesRegularExpression('/^STD\d{6}$/', $first->student_id);
        $this->assertMatchesRegularExpression('/^STD\d{6}$/', $second->student_id);
        $this->assertNotSame($first->student_id, $second->student_id);
    }

    public function test_teacher_id_is_auto_generated_when_missing(): void
    {
        [$university, $department] = $this->organization();

        $first = Teacher::create([
            'university_id' => $university->id,
            'department_id' => $department->id,
            'full_name' => 'Generated Teacher One',
            'email' => 'generated.teacher.one@example.com',
            'status' => 'Active',
        ]);

        $second = Teacher::create([
            'university_id' => $university->id,
            'department_id' => $department->id,
            'full_name' => 'Generated Teacher Two',
            'email' => 'generated.teacher.two@example.com',
            'status' => 'Active',
        ]);

        $this->assertNotEmpty($first->staff_id);
        $this->assertNotEmpty($second->staff_id);
        $this->assertStringStartsWith('TCH', $first->staff_id);
        $this->assertStringStartsWith('TCH', $second->staff_id);
        $this->assertStringNotContainsString('-', $first->staff_id);
        $this->assertStringNotContainsString('-', $second->staff_id);
        $this->assertMatchesRegularExpression('/^TCH\d{6}$/', $first->staff_id);
        $this->assertMatchesRegularExpression('/^TCH\d{6}$/', $second->staff_id);
        $this->assertNotSame($first->staff_id, $second->staff_id);
    }

    private function organization(): array
    {
        $university = University::create([
            'name' => 'Auto ID University',
            'code' => 'AIDU',
        ]);

        $college = College::create([
            'university_id' => $university->id,
            'name' => 'Engineering',
            'code' => 'ENG',
        ]);

        $department = Department::create([
            'university_id' => $university->id,
            'college_id' => $college->id,
            'name' => 'Computer Science',
            'code' => 'CS',
        ]);

        return [$university, $department];
    }
}
