<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
            <div><p class="text-sm font-semibold text-blue-700 dark:text-indigo-300">{{ $course->code }}</p><h2 class="mt-1 text-xl font-semibold text-gray-800 dark:text-gray-100">{{ $course->name }}</h2><p class="text-sm text-gray-600 dark:text-gray-400">{{ __('Read-only course catalog profile and its semester modules.') }}</p></div>
            <div class="flex gap-2"><a href="{{ route('course-records.index') }}" class="rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-200 dark:hover:bg-gray-800">{{ __('Back') }}</a>@if($abilities['update'])<a href="{{ route('course-records.edit', $course) }}" class="rounded-md bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-700 dark:bg-indigo-600 dark:hover:bg-indigo-500">{{ __('Edit Course') }}</a>@endif</div>
        </div>
    </x-slot>
    <div class="py-10"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">
        <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
            <div class="rounded-lg border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-900"><p class="text-sm text-gray-500 dark:text-gray-400">{{ __('All modules') }}</p><p class="mt-2 text-2xl font-semibold text-gray-900 dark:text-gray-100">{{ $summary['sections'] }}</p></div>
            <div class="rounded-lg border border-blue-200 bg-blue-50 p-4 dark:border-blue-900 dark:bg-blue-950/40"><p class="text-sm text-blue-800 dark:text-blue-300">{{ __('Open modules') }}</p><p class="mt-2 text-2xl font-semibold text-blue-950 dark:text-blue-100">{{ $summary['open_sections'] }}</p></div>
            <div class="rounded-lg border border-emerald-200 bg-emerald-50 p-4 dark:border-emerald-900 dark:bg-emerald-950/40"><p class="text-sm text-emerald-800 dark:text-emerald-300">{{ __('Active students') }}</p><p class="mt-2 text-2xl font-semibold text-emerald-950 dark:text-emerald-100">{{ $summary['students'] }}</p></div>
            <div class="rounded-lg border border-violet-200 bg-violet-50 p-4 dark:border-violet-900 dark:bg-violet-950/40"><p class="text-sm text-violet-800 dark:text-violet-300">{{ __('Assessments') }}</p><p class="mt-2 text-2xl font-semibold text-violet-950 dark:text-violet-100">{{ $summary['assessments'] }}</p></div>
        </section>

        <section class="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(260px,0.4fr)]">
            <div class="overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-900">
                <div class="border-b border-gray-200 px-5 py-4 dark:border-gray-800"><h3 class="font-semibold text-gray-900 dark:text-gray-100">{{ __('Semester modules') }}</h3></div>
                <div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 dark:divide-gray-800"><thead class="bg-gray-50 dark:bg-gray-950"><tr><th class="px-5 py-3 text-left text-xs font-medium uppercase text-gray-500">{{ __('Semester / Module') }}</th><th class="px-5 py-3 text-left text-xs font-medium uppercase text-gray-500">{{ __('Teacher') }}</th><th class="px-5 py-3 text-left text-xs font-medium uppercase text-gray-500">{{ __('Students') }}</th><th class="px-5 py-3 text-left text-xs font-medium uppercase text-gray-500">{{ __('Learning') }}</th><th class="px-5 py-3 text-left text-xs font-medium uppercase text-gray-500">{{ __('Status') }}</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">
                    @forelse($course->sections as $section)<tr class="dark:hover:bg-gray-800/70"><td class="px-5 py-4 text-sm font-medium text-gray-900 dark:text-gray-100">{{ $section->semester->name ?? __('No semester') }} {{ $section->semester->academic_year ?? '' }}<p class="mt-1 text-xs text-gray-500 dark:text-gray-400">{{ __('Group :code', ['code' => $section->section_code]) }}{{ $section->grade_level ? ' / '.$section->grade_level : '' }}</p></td><td class="px-5 py-4 text-sm text-gray-600 dark:text-gray-300">{{ $section->teacher->full_name ?? __('Unassigned') }}</td><td class="px-5 py-4 text-sm text-gray-600 dark:text-gray-300">{{ $section->active_enrollments_count }} / {{ $section->capacity }}</td><td class="px-5 py-4 text-sm text-gray-600 dark:text-gray-300">{{ __(':count assessments', ['count' => $section->assessment_items_count]) }}<p class="mt-1 text-xs text-gray-500 dark:text-gray-400">{{ __(':files files / :entries timetable entries', ['files' => $section->materials_count, 'entries' => $section->timetables_count]) }}</p></td><td class="px-5 py-4 text-sm text-gray-600 dark:text-gray-300">{{ __(ucfirst($section->status)) }}</td></tr>
                    @empty<tr><td colspan="5" class="px-5 py-12 text-center text-sm text-gray-500">{{ __('No semester modules have been created.') }}</td></tr>@endforelse
                </tbody></table></div>
            </div>
            <div class="space-y-6">
                <section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-800 dark:bg-gray-900"><h3 class="font-semibold text-gray-900 dark:text-gray-100">{{ __('Catalog details') }}</h3><dl class="mt-4 space-y-4 text-sm dark:text-gray-300"><div><dt class="text-gray-500 dark:text-gray-400">{{ __('University') }}</dt><dd class="mt-1 font-medium text-gray-900 dark:text-gray-100">{{ $course->university->name ?? __('Not assigned') }}</dd></div><div><dt class="text-gray-500 dark:text-gray-400">{{ __('College') }}</dt><dd class="mt-1 font-medium text-gray-900 dark:text-gray-100">{{ $course->department->college->name ?? __('No college') }}</dd></div><div><dt class="text-gray-500 dark:text-gray-400">{{ __('Department') }}</dt><dd class="mt-1 font-medium text-gray-900 dark:text-gray-100">{{ $course->department->name ?? __('No department') }}</dd></div><div><dt class="text-gray-500 dark:text-gray-400">{{ __('Credits') }}</dt><dd class="mt-1 font-medium text-gray-900 dark:text-gray-100">{{ $course->credits }}</dd></div><div><dt class="text-gray-500 dark:text-gray-400">{{ __('Status') }}</dt><dd class="mt-1 font-medium text-gray-900 dark:text-gray-100">{{ __(ucfirst($course->status)) }}</dd></div></dl></section>
                <section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-800 dark:bg-gray-900"><h3 class="font-semibold text-gray-900 dark:text-gray-100">{{ __('Historical records') }}</h3><dl class="mt-4 space-y-4 text-sm"><div class="flex justify-between gap-4"><dt class="text-gray-500 dark:text-gray-400">{{ __('Marks') }}</dt><dd class="font-medium text-gray-900 dark:text-gray-100">{{ $course->marks_count }}</dd></div><div class="flex justify-between gap-4"><dt class="text-gray-500 dark:text-gray-400">{{ __('Attendance records') }}</dt><dd class="font-medium text-gray-900 dark:text-gray-100">{{ $course->attendances_count }}</dd></div><div class="flex justify-between gap-4"><dt class="text-gray-500 dark:text-gray-400">{{ __('Course materials') }}</dt><dd class="font-medium text-gray-900 dark:text-gray-100">{{ $course->materials_count }}</dd></div></dl></section>
            </div>
        </section>
    </div></div>
</x-app-layout>
